/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.milind.avro.order.response;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ConfirmedLineItemRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1587967301116597991L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ConfirmedLineItemRecord\",\"namespace\":\"com.milind.avro.order.response\",\"fields\":[{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"confirmQuantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ConfirmedLineItemRecord> ENCODER =
      new BinaryMessageEncoder<ConfirmedLineItemRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ConfirmedLineItemRecord> DECODER =
      new BinaryMessageDecoder<ConfirmedLineItemRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ConfirmedLineItemRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ConfirmedLineItemRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ConfirmedLineItemRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ConfirmedLineItemRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ConfirmedLineItemRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ConfirmedLineItemRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ConfirmedLineItemRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ConfirmedLineItemRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence sku;
  @Deprecated public int confirmQuantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ConfirmedLineItemRecord() {}

  /**
   * All-args constructor.
   * @param sku The new value for sku
   * @param confirmQuantity The new value for confirmQuantity
   */
  public ConfirmedLineItemRecord(java.lang.CharSequence sku, java.lang.Integer confirmQuantity) {
    this.sku = sku;
    this.confirmQuantity = confirmQuantity;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sku;
    case 1: return confirmQuantity;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sku = (java.lang.CharSequence)value$; break;
    case 1: confirmQuantity = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sku' field.
   * @return The value of the 'sku' field.
   */
  public java.lang.CharSequence getSku() {
    return sku;
  }


  /**
   * Sets the value of the 'sku' field.
   * @param value the value to set.
   */
  public void setSku(java.lang.CharSequence value) {
    this.sku = value;
  }

  /**
   * Gets the value of the 'confirmQuantity' field.
   * @return The value of the 'confirmQuantity' field.
   */
  public int getConfirmQuantity() {
    return confirmQuantity;
  }


  /**
   * Sets the value of the 'confirmQuantity' field.
   * @param value the value to set.
   */
  public void setConfirmQuantity(int value) {
    this.confirmQuantity = value;
  }

  /**
   * Creates a new ConfirmedLineItemRecord RecordBuilder.
   * @return A new ConfirmedLineItemRecord RecordBuilder
   */
  public static com.milind.avro.order.response.ConfirmedLineItemRecord.Builder newBuilder() {
    return new com.milind.avro.order.response.ConfirmedLineItemRecord.Builder();
  }

  /**
   * Creates a new ConfirmedLineItemRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ConfirmedLineItemRecord RecordBuilder
   */
  public static com.milind.avro.order.response.ConfirmedLineItemRecord.Builder newBuilder(com.milind.avro.order.response.ConfirmedLineItemRecord.Builder other) {
    if (other == null) {
      return new com.milind.avro.order.response.ConfirmedLineItemRecord.Builder();
    } else {
      return new com.milind.avro.order.response.ConfirmedLineItemRecord.Builder(other);
    }
  }

  /**
   * Creates a new ConfirmedLineItemRecord RecordBuilder by copying an existing ConfirmedLineItemRecord instance.
   * @param other The existing instance to copy.
   * @return A new ConfirmedLineItemRecord RecordBuilder
   */
  public static com.milind.avro.order.response.ConfirmedLineItemRecord.Builder newBuilder(com.milind.avro.order.response.ConfirmedLineItemRecord other) {
    if (other == null) {
      return new com.milind.avro.order.response.ConfirmedLineItemRecord.Builder();
    } else {
      return new com.milind.avro.order.response.ConfirmedLineItemRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for ConfirmedLineItemRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConfirmedLineItemRecord>
    implements org.apache.avro.data.RecordBuilder<ConfirmedLineItemRecord> {

    private java.lang.CharSequence sku;
    private int confirmQuantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.milind.avro.order.response.ConfirmedLineItemRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.confirmQuantity)) {
        this.confirmQuantity = data().deepCopy(fields()[1].schema(), other.confirmQuantity);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ConfirmedLineItemRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.milind.avro.order.response.ConfirmedLineItemRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sku)) {
        this.sku = data().deepCopy(fields()[0].schema(), other.sku);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.confirmQuantity)) {
        this.confirmQuantity = data().deepCopy(fields()[1].schema(), other.confirmQuantity);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sku' field.
      * @return The value.
      */
    public java.lang.CharSequence getSku() {
      return sku;
    }


    /**
      * Sets the value of the 'sku' field.
      * @param value The value of 'sku'.
      * @return This builder.
      */
    public com.milind.avro.order.response.ConfirmedLineItemRecord.Builder setSku(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sku = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sku' field has been set.
      * @return True if the 'sku' field has been set, false otherwise.
      */
    public boolean hasSku() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sku' field.
      * @return This builder.
      */
    public com.milind.avro.order.response.ConfirmedLineItemRecord.Builder clearSku() {
      sku = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'confirmQuantity' field.
      * @return The value.
      */
    public int getConfirmQuantity() {
      return confirmQuantity;
    }


    /**
      * Sets the value of the 'confirmQuantity' field.
      * @param value The value of 'confirmQuantity'.
      * @return This builder.
      */
    public com.milind.avro.order.response.ConfirmedLineItemRecord.Builder setConfirmQuantity(int value) {
      validate(fields()[1], value);
      this.confirmQuantity = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'confirmQuantity' field has been set.
      * @return True if the 'confirmQuantity' field has been set, false otherwise.
      */
    public boolean hasConfirmQuantity() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'confirmQuantity' field.
      * @return This builder.
      */
    public com.milind.avro.order.response.ConfirmedLineItemRecord.Builder clearConfirmQuantity() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ConfirmedLineItemRecord build() {
      try {
        ConfirmedLineItemRecord record = new ConfirmedLineItemRecord();
        record.sku = fieldSetFlags()[0] ? this.sku : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.confirmQuantity = fieldSetFlags()[1] ? this.confirmQuantity : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ConfirmedLineItemRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<ConfirmedLineItemRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ConfirmedLineItemRecord>
    READER$ = (org.apache.avro.io.DatumReader<ConfirmedLineItemRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sku);

    out.writeInt(this.confirmQuantity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sku = in.readString(this.sku instanceof Utf8 ? (Utf8)this.sku : null);

      this.confirmQuantity = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sku = in.readString(this.sku instanceof Utf8 ? (Utf8)this.sku : null);
          break;

        case 1:
          this.confirmQuantity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










