/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.milind.avro.order.response;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderConfirmation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8779434100736769796L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderConfirmation\",\"namespace\":\"com.milind.avro.order.response\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"ConfirmedLineItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"ConfirmedLineItemRecord\",\"fields\":[{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"confirmQuantity\",\"type\":\"int\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderConfirmation> ENCODER =
      new BinaryMessageEncoder<OrderConfirmation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderConfirmation> DECODER =
      new BinaryMessageDecoder<OrderConfirmation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderConfirmation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderConfirmation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderConfirmation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderConfirmation>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderConfirmation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderConfirmation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderConfirmation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderConfirmation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence orderId;
  @Deprecated public java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> ConfirmedLineItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderConfirmation() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param ConfirmedLineItems The new value for ConfirmedLineItems
   */
  public OrderConfirmation(java.lang.CharSequence orderId, java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> ConfirmedLineItems) {
    this.orderId = orderId;
    this.ConfirmedLineItems = ConfirmedLineItems;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return ConfirmedLineItems;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: ConfirmedLineItems = (java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'ConfirmedLineItems' field.
   * @return The value of the 'ConfirmedLineItems' field.
   */
  public java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> getConfirmedLineItems() {
    return ConfirmedLineItems;
  }


  /**
   * Sets the value of the 'ConfirmedLineItems' field.
   * @param value the value to set.
   */
  public void setConfirmedLineItems(java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> value) {
    this.ConfirmedLineItems = value;
  }

  /**
   * Creates a new OrderConfirmation RecordBuilder.
   * @return A new OrderConfirmation RecordBuilder
   */
  public static com.milind.avro.order.response.OrderConfirmation.Builder newBuilder() {
    return new com.milind.avro.order.response.OrderConfirmation.Builder();
  }

  /**
   * Creates a new OrderConfirmation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderConfirmation RecordBuilder
   */
  public static com.milind.avro.order.response.OrderConfirmation.Builder newBuilder(com.milind.avro.order.response.OrderConfirmation.Builder other) {
    if (other == null) {
      return new com.milind.avro.order.response.OrderConfirmation.Builder();
    } else {
      return new com.milind.avro.order.response.OrderConfirmation.Builder(other);
    }
  }

  /**
   * Creates a new OrderConfirmation RecordBuilder by copying an existing OrderConfirmation instance.
   * @param other The existing instance to copy.
   * @return A new OrderConfirmation RecordBuilder
   */
  public static com.milind.avro.order.response.OrderConfirmation.Builder newBuilder(com.milind.avro.order.response.OrderConfirmation other) {
    if (other == null) {
      return new com.milind.avro.order.response.OrderConfirmation.Builder();
    } else {
      return new com.milind.avro.order.response.OrderConfirmation.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderConfirmation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderConfirmation>
    implements org.apache.avro.data.RecordBuilder<OrderConfirmation> {

    private java.lang.CharSequence orderId;
    private java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> ConfirmedLineItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.milind.avro.order.response.OrderConfirmation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ConfirmedLineItems)) {
        this.ConfirmedLineItems = data().deepCopy(fields()[1].schema(), other.ConfirmedLineItems);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderConfirmation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.milind.avro.order.response.OrderConfirmation other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ConfirmedLineItems)) {
        this.ConfirmedLineItems = data().deepCopy(fields()[1].schema(), other.ConfirmedLineItems);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.milind.avro.order.response.OrderConfirmation.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.milind.avro.order.response.OrderConfirmation.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ConfirmedLineItems' field.
      * @return The value.
      */
    public java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> getConfirmedLineItems() {
      return ConfirmedLineItems;
    }


    /**
      * Sets the value of the 'ConfirmedLineItems' field.
      * @param value The value of 'ConfirmedLineItems'.
      * @return This builder.
      */
    public com.milind.avro.order.response.OrderConfirmation.Builder setConfirmedLineItems(java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> value) {
      validate(fields()[1], value);
      this.ConfirmedLineItems = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ConfirmedLineItems' field has been set.
      * @return True if the 'ConfirmedLineItems' field has been set, false otherwise.
      */
    public boolean hasConfirmedLineItems() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ConfirmedLineItems' field.
      * @return This builder.
      */
    public com.milind.avro.order.response.OrderConfirmation.Builder clearConfirmedLineItems() {
      ConfirmedLineItems = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderConfirmation build() {
      try {
        OrderConfirmation record = new OrderConfirmation();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.ConfirmedLineItems = fieldSetFlags()[1] ? this.ConfirmedLineItems : (java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderConfirmation>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderConfirmation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderConfirmation>
    READER$ = (org.apache.avro.io.DatumReader<OrderConfirmation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    long size0 = this.ConfirmedLineItems.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.milind.avro.order.response.ConfirmedLineItemRecord e0: this.ConfirmedLineItems) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      long size0 = in.readArrayStart();
      java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> a0 = this.ConfirmedLineItems;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.milind.avro.order.response.ConfirmedLineItemRecord>((int)size0, SCHEMA$.getField("ConfirmedLineItems").schema());
        this.ConfirmedLineItems = a0;
      } else a0.clear();
      SpecificData.Array<com.milind.avro.order.response.ConfirmedLineItemRecord> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.milind.avro.order.response.ConfirmedLineItemRecord>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.milind.avro.order.response.ConfirmedLineItemRecord e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.milind.avro.order.response.ConfirmedLineItemRecord();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<com.milind.avro.order.response.ConfirmedLineItemRecord> a0 = this.ConfirmedLineItems;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.milind.avro.order.response.ConfirmedLineItemRecord>((int)size0, SCHEMA$.getField("ConfirmedLineItems").schema());
            this.ConfirmedLineItems = a0;
          } else a0.clear();
          SpecificData.Array<com.milind.avro.order.response.ConfirmedLineItemRecord> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.milind.avro.order.response.ConfirmedLineItemRecord>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.milind.avro.order.response.ConfirmedLineItemRecord e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.milind.avro.order.response.ConfirmedLineItemRecord();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










