/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.milind.avro.order.request;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Order extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5196599055647221658L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Order\",\"namespace\":\"com.milind.avro.order.request\",\"fields\":[{\"name\":\"currency\",\"type\":\"string\"},{\"name\":\"totalAmount\",\"type\":\"float\"},{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"emailAddress\",\"type\":\"string\"},{\"name\":\"cartUrl\",\"type\":[\"string\",\"null\"]},{\"name\":\"lineItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LineItemRecord\",\"fields\":[{\"name\":\"sku\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"description\",\"type\":[\"string\",\"null\"]},{\"name\":\"category\",\"type\":\"string\"},{\"name\":\"other\",\"type\":[\"string\",\"null\"]},{\"name\":\"unitPrice\",\"type\":\"float\"},{\"name\":\"salePrice\",\"type\":\"float\"},{\"name\":\"quantity\",\"type\":\"int\"},{\"name\":\"totalPrice\",\"type\":\"float\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Order> ENCODER =
      new BinaryMessageEncoder<Order>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Order> DECODER =
      new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Order> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Order> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Order> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Order>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Order to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Order from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Order instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Order fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence currency;
  @Deprecated public float totalAmount;
  @Deprecated public java.lang.CharSequence orderId;
  @Deprecated public java.lang.CharSequence emailAddress;
  @Deprecated public java.lang.CharSequence cartUrl;
  @Deprecated public java.util.List<com.milind.avro.order.request.LineItemRecord> lineItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Order() {}

  /**
   * All-args constructor.
   * @param currency The new value for currency
   * @param totalAmount The new value for totalAmount
   * @param orderId The new value for orderId
   * @param emailAddress The new value for emailAddress
   * @param cartUrl The new value for cartUrl
   * @param lineItems The new value for lineItems
   */
  public Order(java.lang.CharSequence currency, java.lang.Float totalAmount, java.lang.CharSequence orderId, java.lang.CharSequence emailAddress, java.lang.CharSequence cartUrl, java.util.List<com.milind.avro.order.request.LineItemRecord> lineItems) {
    this.currency = currency;
    this.totalAmount = totalAmount;
    this.orderId = orderId;
    this.emailAddress = emailAddress;
    this.cartUrl = cartUrl;
    this.lineItems = lineItems;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return currency;
    case 1: return totalAmount;
    case 2: return orderId;
    case 3: return emailAddress;
    case 4: return cartUrl;
    case 5: return lineItems;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: currency = (java.lang.CharSequence)value$; break;
    case 1: totalAmount = (java.lang.Float)value$; break;
    case 2: orderId = (java.lang.CharSequence)value$; break;
    case 3: emailAddress = (java.lang.CharSequence)value$; break;
    case 4: cartUrl = (java.lang.CharSequence)value$; break;
    case 5: lineItems = (java.util.List<com.milind.avro.order.request.LineItemRecord>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'totalAmount' field.
   * @return The value of the 'totalAmount' field.
   */
  public float getTotalAmount() {
    return totalAmount;
  }


  /**
   * Sets the value of the 'totalAmount' field.
   * @param value the value to set.
   */
  public void setTotalAmount(float value) {
    this.totalAmount = value;
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'emailAddress' field.
   * @return The value of the 'emailAddress' field.
   */
  public java.lang.CharSequence getEmailAddress() {
    return emailAddress;
  }


  /**
   * Sets the value of the 'emailAddress' field.
   * @param value the value to set.
   */
  public void setEmailAddress(java.lang.CharSequence value) {
    this.emailAddress = value;
  }

  /**
   * Gets the value of the 'cartUrl' field.
   * @return The value of the 'cartUrl' field.
   */
  public java.lang.CharSequence getCartUrl() {
    return cartUrl;
  }


  /**
   * Sets the value of the 'cartUrl' field.
   * @param value the value to set.
   */
  public void setCartUrl(java.lang.CharSequence value) {
    this.cartUrl = value;
  }

  /**
   * Gets the value of the 'lineItems' field.
   * @return The value of the 'lineItems' field.
   */
  public java.util.List<com.milind.avro.order.request.LineItemRecord> getLineItems() {
    return lineItems;
  }


  /**
   * Sets the value of the 'lineItems' field.
   * @param value the value to set.
   */
  public void setLineItems(java.util.List<com.milind.avro.order.request.LineItemRecord> value) {
    this.lineItems = value;
  }

  /**
   * Creates a new Order RecordBuilder.
   * @return A new Order RecordBuilder
   */
  public static com.milind.avro.order.request.Order.Builder newBuilder() {
    return new com.milind.avro.order.request.Order.Builder();
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Order RecordBuilder
   */
  public static com.milind.avro.order.request.Order.Builder newBuilder(com.milind.avro.order.request.Order.Builder other) {
    if (other == null) {
      return new com.milind.avro.order.request.Order.Builder();
    } else {
      return new com.milind.avro.order.request.Order.Builder(other);
    }
  }

  /**
   * Creates a new Order RecordBuilder by copying an existing Order instance.
   * @param other The existing instance to copy.
   * @return A new Order RecordBuilder
   */
  public static com.milind.avro.order.request.Order.Builder newBuilder(com.milind.avro.order.request.Order other) {
    if (other == null) {
      return new com.milind.avro.order.request.Order.Builder();
    } else {
      return new com.milind.avro.order.request.Order.Builder(other);
    }
  }

  /**
   * RecordBuilder for Order instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Order>
    implements org.apache.avro.data.RecordBuilder<Order> {

    private java.lang.CharSequence currency;
    private float totalAmount;
    private java.lang.CharSequence orderId;
    private java.lang.CharSequence emailAddress;
    private java.lang.CharSequence cartUrl;
    private java.util.List<com.milind.avro.order.request.LineItemRecord> lineItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.milind.avro.order.request.Order.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.currency)) {
        this.currency = data().deepCopy(fields()[0].schema(), other.currency);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[1].schema(), other.totalAmount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.emailAddress)) {
        this.emailAddress = data().deepCopy(fields()[3].schema(), other.emailAddress);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.cartUrl)) {
        this.cartUrl = data().deepCopy(fields()[4].schema(), other.cartUrl);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.lineItems)) {
        this.lineItems = data().deepCopy(fields()[5].schema(), other.lineItems);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Order instance
     * @param other The existing instance to copy.
     */
    private Builder(com.milind.avro.order.request.Order other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.currency)) {
        this.currency = data().deepCopy(fields()[0].schema(), other.currency);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[1].schema(), other.totalAmount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.orderId)) {
        this.orderId = data().deepCopy(fields()[2].schema(), other.orderId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.emailAddress)) {
        this.emailAddress = data().deepCopy(fields()[3].schema(), other.emailAddress);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cartUrl)) {
        this.cartUrl = data().deepCopy(fields()[4].schema(), other.cartUrl);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.lineItems)) {
        this.lineItems = data().deepCopy(fields()[5].schema(), other.lineItems);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.currency = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalAmount' field.
      * @return The value.
      */
    public float getTotalAmount() {
      return totalAmount;
    }


    /**
      * Sets the value of the 'totalAmount' field.
      * @param value The value of 'totalAmount'.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder setTotalAmount(float value) {
      validate(fields()[1], value);
      this.totalAmount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'totalAmount' field has been set.
      * @return True if the 'totalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'totalAmount' field.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder clearTotalAmount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.orderId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'emailAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmailAddress() {
      return emailAddress;
    }


    /**
      * Sets the value of the 'emailAddress' field.
      * @param value The value of 'emailAddress'.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder setEmailAddress(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.emailAddress = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'emailAddress' field has been set.
      * @return True if the 'emailAddress' field has been set, false otherwise.
      */
    public boolean hasEmailAddress() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'emailAddress' field.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder clearEmailAddress() {
      emailAddress = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'cartUrl' field.
      * @return The value.
      */
    public java.lang.CharSequence getCartUrl() {
      return cartUrl;
    }


    /**
      * Sets the value of the 'cartUrl' field.
      * @param value The value of 'cartUrl'.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder setCartUrl(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.cartUrl = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'cartUrl' field has been set.
      * @return True if the 'cartUrl' field has been set, false otherwise.
      */
    public boolean hasCartUrl() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'cartUrl' field.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder clearCartUrl() {
      cartUrl = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'lineItems' field.
      * @return The value.
      */
    public java.util.List<com.milind.avro.order.request.LineItemRecord> getLineItems() {
      return lineItems;
    }


    /**
      * Sets the value of the 'lineItems' field.
      * @param value The value of 'lineItems'.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder setLineItems(java.util.List<com.milind.avro.order.request.LineItemRecord> value) {
      validate(fields()[5], value);
      this.lineItems = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'lineItems' field has been set.
      * @return True if the 'lineItems' field has been set, false otherwise.
      */
    public boolean hasLineItems() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'lineItems' field.
      * @return This builder.
      */
    public com.milind.avro.order.request.Order.Builder clearLineItems() {
      lineItems = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Order build() {
      try {
        Order record = new Order();
        record.currency = fieldSetFlags()[0] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.totalAmount = fieldSetFlags()[1] ? this.totalAmount : (java.lang.Float) defaultValue(fields()[1]);
        record.orderId = fieldSetFlags()[2] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.emailAddress = fieldSetFlags()[3] ? this.emailAddress : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.cartUrl = fieldSetFlags()[4] ? this.cartUrl : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.lineItems = fieldSetFlags()[5] ? this.lineItems : (java.util.List<com.milind.avro.order.request.LineItemRecord>) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Order>
    WRITER$ = (org.apache.avro.io.DatumWriter<Order>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Order>
    READER$ = (org.apache.avro.io.DatumReader<Order>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.currency);

    out.writeFloat(this.totalAmount);

    out.writeString(this.orderId);

    out.writeString(this.emailAddress);

    if (this.cartUrl == null) {
      out.writeIndex(1);
      out.writeNull();
    } else {
      out.writeIndex(0);
      out.writeString(this.cartUrl);
    }

    long size0 = this.lineItems.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.milind.avro.order.request.LineItemRecord e0: this.lineItems) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);

      this.totalAmount = in.readFloat();

      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      this.emailAddress = in.readString(this.emailAddress instanceof Utf8 ? (Utf8)this.emailAddress : null);

      if (in.readIndex() != 0) {
        in.readNull();
        this.cartUrl = null;
      } else {
        this.cartUrl = in.readString(this.cartUrl instanceof Utf8 ? (Utf8)this.cartUrl : null);
      }

      long size0 = in.readArrayStart();
      java.util.List<com.milind.avro.order.request.LineItemRecord> a0 = this.lineItems;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.milind.avro.order.request.LineItemRecord>((int)size0, SCHEMA$.getField("lineItems").schema());
        this.lineItems = a0;
      } else a0.clear();
      SpecificData.Array<com.milind.avro.order.request.LineItemRecord> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.milind.avro.order.request.LineItemRecord>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.milind.avro.order.request.LineItemRecord e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.milind.avro.order.request.LineItemRecord();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
          break;

        case 1:
          this.totalAmount = in.readFloat();
          break;

        case 2:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 3:
          this.emailAddress = in.readString(this.emailAddress instanceof Utf8 ? (Utf8)this.emailAddress : null);
          break;

        case 4:
          if (in.readIndex() != 0) {
            in.readNull();
            this.cartUrl = null;
          } else {
            this.cartUrl = in.readString(this.cartUrl instanceof Utf8 ? (Utf8)this.cartUrl : null);
          }
          break;

        case 5:
          long size0 = in.readArrayStart();
          java.util.List<com.milind.avro.order.request.LineItemRecord> a0 = this.lineItems;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.milind.avro.order.request.LineItemRecord>((int)size0, SCHEMA$.getField("lineItems").schema());
            this.lineItems = a0;
          } else a0.clear();
          SpecificData.Array<com.milind.avro.order.request.LineItemRecord> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.milind.avro.order.request.LineItemRecord>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.milind.avro.order.request.LineItemRecord e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.milind.avro.order.request.LineItemRecord();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










